# Generated by Django 5.0.7 on 2024-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gmail',
            field=models.CharField(default='example@gmail.com', max_length=100),
        ),
    ]
