# Generated by Django 5.0.7 on 2024-08-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0003_formulario_datos_correctos_admincredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
