# Generated by Django 5.0.7 on 2024-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0004_alter_formulario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
