# Generated by Django 5.0.7 on 2024-08-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0005_formulario_fecha_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cartilla.formulario')),
            ],
        ),
    ]
