# Generated by Django 5.0.7 on 2024-08-15 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0006_notificaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaciones',
            new_name='Notificacion',
        ),
    ]
