# Generated by Django 5.0.7 on 2024-08-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0007_rename_notificaciones_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_envio',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartilla.formulario'),
        ),
    ]
