# Generated by Django 5.0.7 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0009_remove_notificacion_formulario_notificacion_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='asunto',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Fallido', 'Fallido')], default='Enviado', max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='message',
            field=models.TextField(default='Mensaje por defecto'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
