# Generated by Django 5.0.7 on 2024-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0011_remove_notificacion_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionDeDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('asunto', models.CharField(default='Asunto predeterminado', max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('creado_a_las', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
