# Generated by Django 5.0.7 on 2024-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartilla', '0012_revisiondedatos_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
